In [1]:
import numpy as np

## Exercício 1

In [5]:
X = np.array([[1,1],
              [1,2],
              [1,3],
              [1,4],
              [1,5],])
y = [[3],[5],[7],[9],[11]]

In [6]:
w = np.matmul(np.matmul((np.linalg.inv(np.matmul(X.T,X))),X.T),y)

In [7]:
w

array([[1.],
       [2.]])

## Exercício 2

In [11]:
X = np.array([[1,1,1],
              [1,2,4],
              [1,3,9],
              [1,4,16],
              [1,5,25],])
y = [[1],[4],[9],[16],[25]]

In [12]:
w = np.matmul(np.matmul((np.linalg.inv(np.matmul(X.T,X))),X.T),y)
w

array([[-5.68434189e-14],
       [ 7.01660952e-14],
       [ 1.00000000e+00]])

## Exercício 3

In [23]:
X = np.array([[1,2],
              [2,3],
              [3,4],
              [4,5],])
y = [[2],[4],[6],[8]]

In [24]:
w = np.matmul(np.matmul((np.linalg.inv(np.matmul(X.T,X))),X.T),y)
w

array([[2.],
       [0.]])

## Exercício 4

In [17]:
X = np.array([[1,2],
              [1,6],
              [1,12],
              [1,20]])
y = [[2],[8],[18],[32]]

In [18]:
w = np.matmul(np.matmul((np.linalg.inv(np.matmul(X.T,X))),X.T),y)
w

array([[-1.73913043],
       [ 1.67391304]])