In [1]:
import numpy as np

## Exercício 1

In [16]:
X = np.array([[1,1],
     [1,2],
     [1,3],
     [1,4],
     [1,5]])
y = np.array([[3],
     [5],
     [7],
     [9],
     [11]])

In [17]:
w = np.matmul(np.matmul(np.linalg.inv(np.matmul(X.T,X)),X.T),y)
w

array([[1.],
       [2.]])

## Exercício 2

In [18]:
X = np.array([[1,1,1],
     [1,2,4],
     [1,3,9],
     [1,4,16],
     [1,5,25]])
y = np.array([[1],
     [4],
     [9],
     [16],
     [25]])

In [19]:
w = np.matmul(np.matmul(np.linalg.inv(np.matmul(X.T,X)),X.T),y)
w

array([[-5.68434189e-14],
       [ 7.01660952e-14],
       [ 1.00000000e+00]])

In [20]:
X = np.array([[1,1],
     [1,2],
     [1,3],
     [1,4],
     [1,5]])
y = np.array([[1],
     [2],
     [3],
     [4],
     [5]])

In [21]:
w = np.matmul(np.matmul(np.linalg.inv(np.matmul(X.T,X)),X.T),y)
w

array([[2.83106871e-15],
       [1.00000000e+00]])

## Exercício 3

In [24]:
X = np.array([[1,2],
     [2,3],
     [3,4],
     [4,5]])
y = np.array([[2],
     [4],
     [6],
     [8]])

In [25]:
w = np.matmul(np.matmul(np.linalg.inv(np.matmul(X.T,X)),X.T),y)
w

array([[2.],
       [0.]])

## Exercício 4

In [30]:
X = np.array([[1,1,2],
     [1,2,6],
     [1,3,12],
     [1,4,20]])
y = np.array([[4],
     [12],
     [24],
     [40]])

In [31]:
w = np.matmul(np.matmul(np.linalg.inv(np.matmul(X.T,X)),X.T),y)
w

array([[ 2.15294449e-12],
       [-5.89750471e-13],
       [ 2.00000000e+00]])